### ISSUE TITLE
Exception when used with TimePickerDialog

### ISSUE THREAD

**Issue by prathimak86** [B3nedikt/restring#77] opened 2021-01-22 11:36 UTC
Following exception is thrown when I use the TimePickerDialog
Is this a known issue? Is there something I can do to resolve this issue?

android.view.InflateException: Binary XML file line #37: Binary XML file line #37: Error inflating class Button
  Caused by: android.view.InflateException: Binary XML file line #37: Error inflating class Button
    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.Button" on path: DexPathList[[zip file "/data/app/com.checkpt.oatmobile-vckrE7QAdjG7AdRp2-Nnzg==/base.apk"],nativeLibraryDirectories=[/data/app/com.checkpt.oatmobile-vckrE7QAdjG7AdRp2-Nnzg==/lib/arm, /system/lib, /system/vendor/lib]]
      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
      at android.view.LayoutInflater.createView(LayoutInflater.java:606)
      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:703)
      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
      at android.view.ViewStub.inflateViewNoAdd(ViewStub.java:269)
      at android.view.ViewStub.inflate(ViewStub.java:302)
      at com.android.internal.app.AlertController.resolvePanel(AlertController.java:514)
      at com.android.internal.app.AlertController.setupView(AlertController.java:538)
      at com.android.internal.app.AlertController.installContent(AlertController.java:275)
      at android.app.AlertDialog.onCreate(AlertDialog.java:425)
      at android.app.Dialog.dispatchOnCreate(Dialog.java:511)
      at android.app.Dialog.show(Dialog.java:342)
      at android.app.TimePickerDialog.show(TimePickerDialog.java:149)
      at androidx.fragment.app.DialogFragment.onStart(Unknown Source:10)
      at androidx.fragment.app.Fragment.w(Unknown Source:16)
      at androidx.fragment.app.FragmentManagerImpl.a(Unknown Source:756)
      at androidx.fragment.app.FragmentManagerImpl.l(Unknown Source:93)
      at androidx.fragment.app.FragmentManagerImpl.a(Unknown Source:42)
      at androidx.fragment.app.a.a(Unknown Source:173)
      at androidx.fragment.app.FragmentManagerImpl.a(Unknown Source:38)
      at androidx.fragment.app.FragmentManagerImpl.b(Unknown Source:113)
      at androidx.fragment.app.FragmentManagerImpl.c(Unknown Source:88)
      at androidx.fragment.app.FragmentManagerImpl.m(Unknown Source:21)
      at androidx.fragment.app.FragmentManagerImpl$b.run(Unknown Source:2)
      at android.os.Handler.handleCallback(Handler.java:790)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at android.os.Looper.loop(Looper.java:164)
      at android.app.ActivityThread.main(ActivityThread.java:7000)
      at java.lang.reflect.Method.invoke(Method.java:-2)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by B3nedikt** [comment] 2021-01-22 15:40
@prathimak86 This is not a known issue, I just tried it myself and TimePickerDialog works for me.
Which versions of appcompat, ViewPump & restring are you using?

**Comment by prathimak86** [comment] 2021-01-24 02:02
Hi,
These are the versions which I am using

androidx.appcompat:appcompat:1.1.0
dev.b3nedikt.restring:restring:5.1.1
dev.b3nedikt.viewpump:viewpump:4.0.5
dev.b3nedikt.reword:reword:3.1.0

**Comment by B3nedikt** [comment] 2021-01-24 20:42
I would recommend updating appcompat to 1.2.0, but that does not explain the crash. I cannot do more from my side here. Please fork this repository and change the example app so it reproduces your bug.

This looks weird though:
```
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.Button" on path: DexPathList[[zip file "/data/app/com.checkpt.oatmobile-vckrE7QAdjG7AdRp2-Nnzg==/base.apk"],nativeLibraryDirectories=[/data/app/com.checkpt.oatmobile-vckrE7QAdjG7AdRp2-Nnzg==/lib/arm, /system/lib, /system/vendor/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
```
Probably something about the way you integrate the dialog triggers this, maybe connected to proguard.

**Comment by B3nedikt** [comment] 2021-01-25 20:41
Anyway I am closing this for now, if you manage to reproduce your issue with a fork of my libs example app feel free to open this issue again or open a PR if you think you fixed the issue :)

**Comment by prateekvijay** [comment] 2021-02-15 21:53
It happens in android version 8.1

**Comment by B3nedikt** [comment] 2021-02-18 21:10
@prateekvijay I just tested this, and managed to reproduce the crash on android 8.1 as well. No clue were the crash comes from though, I might look into it on the weekend if I find the time.

**Comment by prathimak86** [comment] 2021-02-22 07:21
Yes this happens in 8.1 and Android 9 too.

**Comment by ravipardeshi02** [comment] 2021-02-23 06:49
any updates on this bug?

**Comment by B3nedikt** [comment] 2021-02-23 21:47
Just fixed it with ViewPump 4.0.6 :)

**Closed by B3nedikt** 2021-02-23 21:47 UTC

**Comment by ravipardeshi02** [comment] 2021-02-24 08:18
Thank you very much Benedikt. It is working perfectly now.

**Comment by B3nedikt** [comment] 2021-02-24 22:54
You`re welcome :)

**Comment by jorgecasariego** [comment] 2021-03-23 20:19
Thanks @B3nedikt 

After updating ViewPump is working fine!
