### ISSUE TITLE
Library is not correctly working with WebView spinners

### ISSUE THREAD

**Issue by edgar-zigis** [B3nedikt/restring#34] opened 2020-08-10 18:38 UTC
There is an issue when library is used in the app having webviews with spinner options like this:

![Screenshot_1597084582](https://user-images.githubusercontent.com/2557008/89817941-9eb94f80-db51-11ea-8526-8d580eabb972.png)

It somehow tries to inflate it as Android element and fails as it tries to provide resource with id 0.

Full error stack:
```
Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x0
       at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:220)
       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2134)
       at android.content.res.Resources.getLayout(Resources.java:1143)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.java:48)
       at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:416)
       at android.widget.ArrayAdapter.getView(ArrayAdapter.java:407)
       at bX2.getView(bX2.java:2)
       at android.widget.AbsListView.obtainView(AbsListView.java:2365)
       at android.widget.ListView.measureHeightOfChildren(ListView.java:1408)
       at android.widget.ListView.onMeasure(ListView.java:1315)
       at android.view.View.measure(View.java:22248)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6682)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:22248)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6682)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:22248)
       at com.android.internal.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:144)
       at com.android.internal.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:69)
       at android.view.View.measure(View.java:22248)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6682)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:22248)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6682)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
       at android.view.View.measure(View.java:22248)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6682)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:740)
       at android.view.View.measure(View.java:22248)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2546)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1537)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1832)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1452)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7043)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:916)
       at android.view.Choreographer.doCallbacks(Choreographer.java:728)
       at android.view.Choreographer.doFrame(Choreographer.java:660)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:902)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6548)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
```

**Comment by edgar-zigis** [comment] 2020-08-10 18:46
Just want to make sure, this issue occurs in appcompat 1.1.0
If updated to appcompat 1.2.0, then this issue disappears everywhere except on API26, but nigh mode change issues appear which I did state in another ticket 😆 

I would not be surprised that the appcompat guys did f**k up something, because they are bonafide losers as their api always hangs on a thread.

**Comment by edgar-zigis** [comment] 2020-08-11 12:33
@B3nedikt I am able to reproduce this issue in the latest fork when using API 26 device.
Everything works fine in API 21, 29 at least.
It only occurs when having this library though..

**Comment by edgar-zigis** [comment] 2020-08-11 12:35
Stack trace:

```
2020-08-11 15:34:26.601 32281-32281/dev.b3nedikt.restring.example W/System.err: android.view.InflateException: Binary XML file line #26: Binary XML file line #44: Error inflating class com.android.internal.widget.DialogTitle
2020-08-11 15:34:26.601 32281-32281/dev.b3nedikt.restring.example W/System.err: Caused by: android.view.InflateException: Binary XML file line #44: Error inflating class com.android.internal.widget.DialogTitle
2020-08-11 15:34:26.602 32281-32281/dev.b3nedikt.restring.example W/System.err: Caused by: java.lang.reflect.InvocationTargetException
2020-08-11 15:34:26.602 32281-32281/dev.b3nedikt.restring.example W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
2020-08-11 15:34:26.602 32281-32281/dev.b3nedikt.restring.example W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
2020-08-11 15:34:26.602 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:647)
2020-08-11 15:34:26.602 32281-32281/dev.b3nedikt.restring.example W/System.err:     at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.createCustomViewInternal(-ViewPumpLayoutInflater.kt:220)
2020-08-11 15:34:26.602 32281-32281/dev.b3nedikt.restring.example W/System.err:     at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.access$createCustomViewInternal(-ViewPumpLayoutInflater.kt:19)
2020-08-11 15:34:26.602 32281-32281/dev.b3nedikt.restring.example W/System.err:     at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$PrivateWrapperFactory2ViewCreator.onCreateView(-ViewPumpLayoutInflater.kt:421)
2020-08-11 15:34:26.602 32281-32281/dev.b3nedikt.restring.example W/System.err:     at io.github.inflationx.viewpump.internal.-FallbackViewCreationInterceptor.intercept(-FallbackViewCreationInterceptor.kt:14)
2020-08-11 15:34:26.603 32281-32281/dev.b3nedikt.restring.example W/System.err:     at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
2020-08-11 15:34:26.603 32281-32281/dev.b3nedikt.restring.example W/System.err:     at dev.b3nedikt.reword.RewordInterceptor.intercept(RewordInterceptor.kt:13)
2020-08-11 15:34:26.603 32281-32281/dev.b3nedikt.restring.example W/System.err:     at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
2020-08-11 15:34:26.603 32281-32281/dev.b3nedikt.restring.example W/System.err:     at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.kt:36)
2020-08-11 15:34:26.603 32281-32281/dev.b3nedikt.restring.example W/System.err:     at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$PrivateWrapperFactory2.onCreateView(-ViewPumpLayoutInflater.kt:399)
2020-08-11 15:34:26.603 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
2020-08-11 15:34:26.603 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
2020-08-11 15:34:26.603 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
2020-08-11 15:34:26.603 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
2020-08-11 15:34:26.603 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
2020-08-11 15:34:26.604 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
2020-08-11 15:34:26.604 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
2020-08-11 15:34:26.604 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:995)
2020-08-11 15:34:26.604 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
2020-08-11 15:34:26.604 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
2020-08-11 15:34:26.604 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
2020-08-11 15:34:26.604 32281-32281/dev.b3nedikt.restring.example W/System.err:     at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:57)
2020-08-11 15:34:26.604 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
2020-08-11 15:34:26.604 32281-32281/dev.b3nedikt.restring.example W/System.err:     at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:48)
2020-08-11 15:34:26.605 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
2020-08-11 15:34:26.605 32281-32281/dev.b3nedikt.restring.example W/System.err:     at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:461)
2020-08-11 15:34:26.605 32281-32281/dev.b3nedikt.restring.example W/System.err:     at com.android.internal.app.AlertController.installContent(AlertController.java:274)
2020-08-11 15:34:26.605 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.app.AlertDialog.onCreate(AlertDialog.java:425)
2020-08-11 15:34:26.605 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.app.Dialog.dispatchOnCreate(Dialog.java:494)
2020-08-11 15:34:26.605 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.app.Dialog.show(Dialog.java:342)
2020-08-11 15:34:26.605 32281-32281/dev.b3nedikt.restring.example W/System.err:     at gX2.a(chromium-Monochrome.aab-stable-414711173:1)
2020-08-11 15:34:26.605 32281-32281/dev.b3nedikt.restring.example W/System.err:     at org.chromium.content.browser.input.SelectPopup.show(chromium-Monochrome.aab-stable-414711173:14)
2020-08-11 15:34:26.605 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2020-08-11 15:34:26.605 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:325)
2020-08-11 15:34:26.605 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.os.Looper.loop(Looper.java:142)
2020-08-11 15:34:26.606 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6944)
2020-08-11 15:34:26.606 32281-32281/dev.b3nedikt.restring.example W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-08-11 15:34:26.606 32281-32281/dev.b3nedikt.restring.example W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
2020-08-11 15:34:26.606 32281-32281/dev.b3nedikt.restring.example W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
2020-08-11 15:34:26.606 32281-32281/dev.b3nedikt.restring.example W/System.err: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
2020-08-11 15:34:26.607 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.content.res.TypedArray.getColorStateList(TypedArray.java:538)
2020-08-11 15:34:26.607 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.widget.TextView.<init>(TextView.java:1255)
2020-08-11 15:34:26.607 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.widget.TextView.<init>(TextView.java:1145)
2020-08-11 15:34:26.607 32281-32281/dev.b3nedikt.restring.example W/System.err:     at android.widget.TextView.<init>(TextView.java:1141)
2020-08-11 15:34:26.607 32281-32281/dev.b3nedikt.restring.example W/System.err:     at com.android.internal.widget.DialogTitle.<init>(DialogTitle.java:41)
2020-08-11 15:34:26.607 32281-32281/dev.b3nedikt.restring.example W/System.err: 	... 41 more
```

**Comment by B3nedikt** [comment] 2020-08-11 14:23
I can´t reproduce this issue in the emulator with your fork on API 26.
Can you check if this issue appears for you only with real devices, but not with the emulator?

**Comment by edgar-zigis** [comment] 2020-08-11 14:28
Yeah, on emulator it works.. but I think the issues can be closed. The problem is clearly with ViewPump library which is already quite dated and there are similar issues on their issue tracker.
Because OTA strings are quite important for us, I will try to fork ViewPump and attempt to fix the issue.

**Comment by B3nedikt** [comment] 2020-08-11 14:47
Okay, I am closing the issue then. Androids view inflation is sometimes a bit weird, would be cool if you can find a fix for the issue :)

The only workaround I can think off would be to use ViewPump to replace the "DialogTitle" with a simple TextView using a ViewPump pre inflation interceptor.

**Closed by B3nedikt** 2020-08-11 14:47 UTC

**Comment by B3nedikt** [comment] 2020-08-16 19:57
@edgar-zigis Hi, I remembered I had a similar issue in the past.
I think your issue is not caused by ViewPump, but simply by using a wrong theme.

See this line in your log:
```
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
```

This error is thrown in the constructor of the DialogTitle view.
The typed value array in this constructor does not contain the requested attribute with index 6, therefor it cannot inflate the DialogTitle view which the web view uses to display the title of the spinner dialog. One reason for this could be that the attribute simply does not exist in the used theme!

I created a branch here which demonstrates the fix: https://github.com/B3nedikt/restring/tree/night_mode_toogle_test
As I can´t reproduce your issue I can´t say if it works though... Please try it out ;)

**Comment by edgar-zigis** [comment] 2020-08-17 02:57
Thanks, already working on it 👍

**Comment by edgar-zigis** [comment] 2020-08-20 06:42
@B3nedikt unfortunately the only fix for us was to move webviews into separate activity which does not localize stuff with Restring. Because just disabling restring temporarily did not work. We even tried to pass resources from application context instead of the restring context. The resources are still being weirdly overrided by the previously attached resources from attachBaseContext, although calls to the getResources() are being made.

**Comment by edgar-zigis** [comment] 2020-08-20 06:42
Thank you for the investigation though!
